/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : string,
  'updatedAt' : bigint,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface BlogPostInput {
  'status' : string,
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : string,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'service' : string,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface _SERVICE {
  'createBlogPost' : ActorMethod<[BlogPostInput], bigint>,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateBlogPost' : ActorMethod<[bigint, BlogPostInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];